"""add session engagement

Revision ID: 10022223c091
Revises: f7a99f00bab7
Create Date: 2026-09-22 09:54:07.995510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10022223c091'
down_revision: Union[str, Sequence[str], None] = 'f7a99f00bab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_engagement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teaching_session_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('data_origin', sa.String(length=20), server_default='PRODUCTION', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_origin IN ('PRODUCTION', 'DEMO', 'TEST')", name='ck_session_engagement_data_origin'),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_session_engagement_score'),
    sa.ForeignKeyConstraint(['teaching_session_id'], ['teaching_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teaching_session_id', name='uq_session_engagement_teaching_session')
    )
    op.create_index(op.f('ix_session_engagement_teaching_session_id'), 'session_engagement', ['teaching_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_engagement_teaching_session_id'), table_name='session_engagement')
    op.drop_table('session_engagement')
    # ### end Alembic commands ###
