"""add session tlm

Revision ID: 645b18b1ec08
Revises: e7142762c4e0
Create Date: 2026-09-24 06:04:13.688479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645b18b1ec08'
down_revision: Union[str, Sequence[str], None] = 'e7142762c4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_tlms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teaching_session_id', sa.Uuid(), nullable=False),
    sa.Column('tlm_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('usage', sa.Text(), nullable=True),
    sa.Column('photo_id', sa.Uuid(), nullable=True),
    sa.Column('data_origin', sa.String(length=20), server_default='PRODUCTION', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_origin IN ('PRODUCTION', 'DEMO', 'TEST')", name='ck_session_tlm_data_origin'),
    sa.CheckConstraint('quantity >= 0', name='ck_session_tlm_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teaching_session_id'], ['teaching_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tlm_id'], ['tlm.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id'),
    sa.UniqueConstraint('teaching_session_id', 'tlm_id', name='uq_session_tlm_session_tlm')
    )
    op.create_index(op.f('ix_session_tlms_teaching_session_id'), 'session_tlms', ['teaching_session_id'], unique=False)
    op.create_index(op.f('ix_session_tlms_tlm_id'), 'session_tlms', ['tlm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_tlms_tlm_id'), table_name='session_tlms')
    op.drop_index(op.f('ix_session_tlms_teaching_session_id'), table_name='session_tlms')
    op.drop_table('session_tlms')
    # ### end Alembic commands ###
