"""add teaching sessions

Revision ID: 749538f86909
Revises: 6ad679cd0e35
Create Date: 2026-09-21 10:52:55.326888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749538f86909'
down_revision: Union[str, Sequence[str], None] = '6ad679cd0e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('class_division_id', sa.Uuid(), nullable=False),
    sa.Column('para_teacher_id', sa.Uuid(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('planned_start_time', sa.Time(), nullable=True),
    sa.Column('planned_end_time', sa.Time(), nullable=True),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PLANNED', nullable=False),
    sa.Column('remarks', sa.String(length=2000), nullable=True),
    sa.Column('feedback_submitted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_origin', sa.String(length=20), server_default='PRODUCTION', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_origin IN ('PRODUCTION', 'DEMO', 'TEST')", name='ck_teaching_session_data_origin'),
    sa.CheckConstraint("status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')", name='ck_teaching_session_status'),
    sa.CheckConstraint('(planned_start_time IS NULL AND planned_end_time IS NULL) OR (planned_start_time IS NOT NULL AND planned_end_time IS NOT NULL AND planned_end_time > planned_start_time)', name='ck_teaching_session_planned_time_range'),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes >= 0', name='ck_teaching_session_duration'),
    sa.ForeignKeyConstraint(['class_division_id'], ['class_divisions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['para_teacher_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_sessions_class_division_id'), 'teaching_sessions', ['class_division_id'], unique=False)
    op.create_index(op.f('ix_teaching_sessions_para_teacher_id'), 'teaching_sessions', ['para_teacher_id'], unique=False)
    op.create_index(op.f('ix_teaching_sessions_session_date'), 'teaching_sessions', ['session_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teaching_sessions_session_date'), table_name='teaching_sessions')
    op.drop_index(op.f('ix_teaching_sessions_para_teacher_id'), table_name='teaching_sessions')
    op.drop_index(op.f('ix_teaching_sessions_class_division_id'), table_name='teaching_sessions')
    op.drop_table('teaching_sessions')
    # ### end Alembic commands ###
