"""add session evidence

Revision ID: 7964c4b6cabb
Revises: 645b18b1ec08
Create Date: 2026-09-24 10:31:53.636728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7964c4b6cabb'
down_revision: Union[str, Sequence[str], None] = '645b18b1ec08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teaching_session_id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('data_origin', sa.String(length=20), server_default=sa.text("'PRODUCTION'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_origin IN ('PRODUCTION', 'DEMO', 'TEST')", name='ck_session_evidence_data_origin'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teaching_session_id'], ['teaching_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teaching_session_id', name='uq_session_evidence_teaching_session')
    )
    op.create_index(op.f('ix_session_evidence_photo_id'), 'session_evidence', ['photo_id'], unique=True)
    op.create_index(op.f('ix_session_evidence_teaching_session_id'), 'session_evidence', ['teaching_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_evidence_teaching_session_id'), table_name='session_evidence')
    op.drop_index(op.f('ix_session_evidence_photo_id'), table_name='session_evidence')
    op.drop_table('session_evidence')
    # ### end Alembic commands ###
