"""add class divisions and students

Revision ID: 8f8f0d6214df
Revises: a9c9d74006f4
Create Date: 2026-09-19 05:41:42.537641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8f0d6214df'
down_revision: Union[str, Sequence[str], None] = 'a9c9d74006f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_divisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('class_level', sa.SmallInteger(), nullable=False),
    sa.Column('division', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_class_division_status'),
    sa.CheckConstraint('class_level IN (5, 6, 7)', name='ck_class_division_class_level'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'class_level', 'division', name='uq_class_division_school_level_division')
    )
    op.create_index(op.f('ix_class_divisions_school_id'), 'class_divisions', ['school_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_code', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('roll_no', sa.SmallInteger(), nullable=False),
    sa.Column('class_division_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_student_status'),
    sa.CheckConstraint('roll_no > 0 AND roll_no <= 999', name='ck_student_roll_no_range'),
    sa.ForeignKeyConstraint(['class_division_id'], ['class_divisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_division_id', 'roll_no', name='uq_student_class_division_roll_no')
    )
    op.create_index(op.f('ix_students_class_division_id'), 'students', ['class_division_id'], unique=False)
    op.create_index(op.f('ix_students_student_code'), 'students', ['student_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_student_code'), table_name='students')
    op.drop_index(op.f('ix_students_class_division_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_class_divisions_school_id'), table_name='class_divisions')
    op.drop_table('class_divisions')
    # ### end Alembic commands ###
