"""add photo model

Revision ID: e7142762c4e0
Revises: 09d1bc1c1588
Create Date: 2026-09-24 04:50:18.852724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7142762c4e0'
down_revision: Union[str, Sequence[str], None] = '09d1bc1c1588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('photo_category', sa.String(length=30), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('data_origin', sa.String(length=20), server_default='PRODUCTION', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_type = 'image/jpeg'", name='ck_photo_content_type'),
    sa.CheckConstraint("data_origin IN ('PRODUCTION', 'DEMO', 'TEST')", name='ck_photo_data_origin'),
    sa.CheckConstraint("photo_category IN ('SESSION_EVIDENCE', 'TLM_ACTIVITY', 'STEM_INSPECTION')", name='ck_photo_category'),
    sa.CheckConstraint('file_size_bytes > 0 AND file_size_bytes <= 1048576', name='ck_photo_file_size'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_photo_latitude'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_photo_longitude'),
    sa.CheckConstraint('width > 0 AND height > 0', name='ck_photo_dimensions'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
