"""add session attendance

Revision ID: f7a99f00bab7
Revises: 749538f86909
Create Date: 2026-09-22 07:21:24.949889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a99f00bab7'
down_revision: Union[str, Sequence[str], None] = '749538f86909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_attendance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teaching_session_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_origin', sa.String(length=20), server_default='PRODUCTION', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_origin IN ('PRODUCTION', 'DEMO', 'TEST')", name='ck_session_attendance_data_origin'),
    sa.CheckConstraint("status IN ('PRESENT', 'ABSENT')", name='ck_session_attendance_status'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teaching_session_id'], ['teaching_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teaching_session_id', 'student_id', name='uq_session_attendance_session_student')
    )
    op.create_index(op.f('ix_session_attendance_student_id'), 'session_attendance', ['student_id'], unique=False)
    op.create_index(op.f('ix_session_attendance_teaching_session_id'), 'session_attendance', ['teaching_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_attendance_teaching_session_id'), table_name='session_attendance')
    op.drop_index(op.f('ix_session_attendance_student_id'), table_name='session_attendance')
    op.drop_table('session_attendance')
    # ### end Alembic commands ###
